### PR TITLE
Fix `new Map()` always returning `Map<unknown, unknown>`

### LINKED ISSUE #206: As of `0.6.0`, `new Map()` cannot satisfy existing generic constraints
Related #41, and specifically - this bug was introduced in #53.

---

Previously (when `new Map()` returned a `Map<any, any>`) - this would have worked:

```ts
function expectsBooleanMap(map: Map<string, boolean>) {}
expectsBooleanMap(new Map());
```

But with `0.6.0` it no longer works!

```
error TS2345: Argument of type 'Map<unknown, unknown>' is not assignable to parameter of type 'Map<string, boolean>'.
```

This also reproduces with usages such as:

```ts
const map: Map<string, boolean> = new Map();
const map = new Map() satisfies Map<string, boolean>;
```

### PR DESCRIPTION
**Pull request by amitdahan**
Closes #206

### CODE REVIEW

File: src/tests/map-constructor.ts [hunk 1]
```diff
@@ -59,3 +59,16 @@ doNotExecute(() => {
 
   type testClear = [Expect<Equal<typeof cleared, void>>];
 });
+
+doNotExecute(() => {
+  const map = new Map() satisfies Map<string, boolean>;
+  type test = [Expect<Equal<typeof map, Map<string, boolean>>>];
+});
+
+doNotExecute(() => {
```
Comment (mattpocock) [inline src/tests/map-constructor.ts:68]: Could you add another test, testing:

`const map: Map<string, boolean> = new Map();`

Comment (amitdahan) [reply src/tests/map-constructor.ts:68]: Of course.

Want me to also add a test with passing to a function accepting a specific map?
Or is that included in one of the 2?

Comment (mattpocock) [reply src/tests/map-constructor.ts:68]: Why not!

Comment (amitdahan) [reply src/tests/map-constructor.ts:68]: Done & done!

**Comment by mattpocock** [comment]
Wonderful, thanks so much!
